ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'IMAGE';
ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'ADMIN';

ALTER TABLE "Message" ALTER COLUMN "body" SET DEFAULT '';
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "mediaUrl" TEXT;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "mediaPublicId" TEXT;
