import { prisma } from "@/lib/prisma";
import { requireAuth } from "@/lib/auth";
import { formatCurrency } from "@/lib/utils";

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await requireAuth();
  const { id } = await params;
  if (!user) return new Response("Unauthorized", { status: 401 });

  const booking = await prisma.booking.findUnique({
    where: { id },
    include: { listing: true, vendor: true, payments: true },
  });

  if (!booking || (booking.customerId !== user.id && user.role !== "ADMIN")) {
    return new Response("Not found", { status: 404 });
  }

  const paid = booking.payments
    .filter((p) => p.status === "SUCCESS")
    .reduce((sum, p) => sum + p.amount, 0);
  const balanceDue = Math.max(0, booking.totalAmount - booking.rewardsRedeemed - paid);
  const shortId = id.slice(0, 8);
  const filename = `evendor-receipt-${shortId}.html`;

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Evendor Receipt ${escapeHtml(shortId)}</title>
<style>
body{font-family:Georgia,"Times New Roman",serif;max-width:640px;margin:40px auto;padding:24px;color:#1c1917;background:#faf8f6}
h1{font-family:system-ui,sans-serif;color:#7A2E3D;margin:0 0 8px}
.meta{color:#78716c;font-size:14px;margin-bottom:24px}
table{width:100%;border-collapse:collapse;margin-top:16px;font-family:system-ui,sans-serif;font-size:14px}
td,th{padding:10px 8px;border-bottom:1px solid #e7e5e4;text-align:left}
th{color:#78716c;font-weight:600}
.total{font-weight:700}
.footer{margin-top:32px;color:#a8a29e;font-size:12px;font-family:system-ui,sans-serif}
@media print{body{margin:0;background:#fff}}
</style></head>
<body>
<h1>Evendor Receipt</h1>
<p class="meta">Booking ${escapeHtml(booking.id)} · Generated ${new Date().toLocaleString()}</p>
<p><strong>Vendor:</strong> ${escapeHtml(booking.vendor.businessName)}</p>
<p><strong>Listing:</strong> ${escapeHtml(booking.listing.title)}</p>
<p><strong>Event:</strong> ${new Date(booking.eventDate).toLocaleDateString()}</p>
<table>
<tr><th>Description</th><th>Amount</th></tr>
<tr><td>Total</td><td>${formatCurrency(booking.totalAmount)}</td></tr>
${
  booking.rewardsRedeemed > 0
    ? `<tr><td>Evendor Rewards applied</td><td>−${formatCurrency(booking.rewardsRedeemed)}</td></tr>`
    : ""
}
<tr><td>Amount paid</td><td class="total">${formatCurrency(paid)}</td></tr>
<tr><td>Balance due</td><td>${formatCurrency(balanceDue)}</td></tr>
<tr><td>Status</td><td>${escapeHtml(booking.status.replace("_", " "))}</td></tr>
</table>
<p class="footer">Generated by Evendor · Save or print this page for your records.</p>
<script>window.addEventListener("load",function(){/* printable receipt */});</script>
</body></html>`;

  return new Response(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "private, no-store",
    },
  });
}
