import { prisma } from "@/lib/prisma";
import { requireAuth } from "@/lib/auth";
import { formatCurrency } from "@/lib/utils";

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await requireAuth();
  const { id } = await params;
  if (!user) return new Response("Unauthorized", { status: 401 });

  const booking = await prisma.booking.findUnique({
    where: { id },
    include: { listing: true, vendor: true, payments: true },
  });

  if (!booking || (booking.customerId !== user.id && user.role !== "ADMIN")) {
    return new Response("Not found", { status: 404 });
  }

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Invoice ${id.slice(0, 8)}</title>
<style>body{font-family:system-ui;max-width:640px;margin:40px auto;padding:24px}
h1{color:#7c3aed}table{width:100%;border-collapse:collapse;margin-top:24px}
td,th{padding:8px;border-bottom:1px solid #eee;text-align:left}</style></head>
<body>
<h1>Evendor Invoice</h1>
<p>Booking ID: ${booking.id}</p>
<p>Vendor: ${booking.vendor.businessName}</p>
<p>Listing: ${booking.listing.title}</p>
<p>Event: ${new Date(booking.eventDate).toLocaleDateString()}</p>
<table>
<tr><th>Description</th><th>Amount</th></tr>
<tr><td>Total</td><td>${formatCurrency(booking.totalAmount)}</td></tr>
<tr><td>Deposit (${booking.depositPercent}%)</td><td>${formatCurrency(booking.depositAmount)}</td></tr>
<tr><td>Status</td><td>${booking.status}</td></tr>
</table>
<p style="margin-top:32px;color:#666;font-size:12px">Generated by Evendor · evendor.app</p>
</body></html>`;

  return new Response(html, {
    headers: { "Content-Type": "text/html" },
  });
}
